# GitHub Sponsors configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [YOUR_GITHUB_USERNAME]
# patreon: YOUR_PATREON_USERNAME
# open_collective: YOUR_OPENCOLLECTIVE_USERNAME
# ko_fi: YOUR_KO_FI_USERNAME
# tidelift: npm/package-name
# custom: ['https://www.buymeacoffee.com/YOUR_USERNAME']
